sylius_ui:
    events:
        sylius.admin.channel.form.second_column_content:
            blocks:
                invoice_request:
                    template: '@LemisoftSyliusInvoiceRequestPlugin/Admin/Channel/Form/_gus_data.html.twig'
                    priority: 11
        sylius.shop.layout.javascripts:
            blocks:
                invoice_request:
                    template: '@LemisoftSyliusInvoiceRequestPlugin/Shop/Checkout/address_js.html.twig'
                    priority: 11
