name: e-commerce-boilerplate
services:
    app:
        image: gitlab.lemisoft.pl:5050/e-commerce/docker-images/sylius-docker-standard:traditional
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://sylius:${MYSQL_PASSWORD:-nopassword}@mysql/sylius?charset=utf8mb4"
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
            XDEBUG_MODE: "coverage"
        volumes:
            - ./:/app
            - ./docker/php/php.ini:/etc/php/8.2/cli/php.ini:delegated
            - ./docker/php/php.ini:/etc/php/8.2/fpm/php.ini:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - 80:80
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
            - MYSQL_DATABASE=sylius
            - MYSQL_USER=sylius
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
        ports:
            - ${MYSQL_PORT:-3306}:3306
        networks:
            - sylius
        volumes:
            - mysql-data:/var/lib/mysql:rw

networks:
    sylius:
        driver: bridge

volumes:
    mysql-data:
